SET PATH=D:\Software\keil_v5\ARM\ARMCC\Bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Python39\Scripts\;C:\Python39\;C:\Program Files (x86)\Razer Chroma SDK\bin;C:\Program Files\Razer Chroma SDK\bin;C:\Program Files (x86)\Razer\ChromaBroadcast\bin;C:\Program Files\Razer\ChromaBroadcast\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Users\16478\AppData\Local\Microsoft\WindowsApps;C:\Windows\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Program Files\dotnet\;C:\Program Files\Git\cmd;D:\Program Files\PuTTY\;D:\Program Files\MATLAB\R2022a\bin;C:\Users\16478\AppData\Local\Microsoft\WindowsApps;;C:\Users\16478\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\16478\AppData\Roaming\npm
SET CPU_TYPE=LPC1768
SET CPU_VENDOR=NXP
SET UV2_TARGET=AE Lib RAM
SET CPU_CLOCK=0x00B71B00
"D:\Software\keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\objects\ram\ae.__i"
"D:\Software\keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\objects\ram\ae_tasks_util.__i"
"D:\Software\keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\objects\ram\ae_timer.__i"
"D:\Software\keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\objects\ram\ae_util.__i"
"D:\Software\keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\objects\ram\main.__i"
"D:\Software\keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\objects\ram\ae_tasks10_g39.__i"
"D:\Software\keil_v5\ARM\ARMCC\Bin\ArmAr" --Via ".\Objects\RAM\ArInp.Scr"
